<?php

namespace backend\controllers;

use yii\web\Controller;

/**
 */
class BaseController extends Controller
{
    const PERMISSION_EXCEPTION = [
        'storage' => [
            'upload',
            'upload-template',
            'upload-png',
            'upload-book-png',
            'upload-delete',
            'upload-imperavi'
        ],
        'site' =>[
            'download',
        ],
        'manager' =>[
            'connector',
        ],
        'model-hint' => [
            'update-tooltip'
        ]
    ];

    public $settings;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}
